# -*- coding: utf-8 -*-
"""P1_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I9gzpD9j-5RDNgaetfmXXY1T1kjXU8P7
"""

x1,y1 = map(int,input().split())
x2,y2 = map(int,input().split())
if -1<=x1-x2<=1 and -1<=y1-y2<=1:
  if checkerboard[x2][y2] == 0:
    print("Yes")
  else:
    print("No")
else:
  print("No")